[package]
name = "grrs"
version = "0.1.0"
edition = "2024"
authors = ["Davi Moreira Fuzatto <davimoreiraf@gmailcom>"]

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.0", features = ["derive"] }
